apiVersion: apps/v1
kind: Deployment
metadata:
  name: shredis-deployment
spec:
  selector:
    matchLabels:
      app: shredis
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: shredis
        version: v1
    spec:
      containers:
      - name: shredis
        image: shredis
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: shredis-service
spec:
  selector:
    app: shredis
  type: LoadBalancer
  ports:
    - name: shredis-port
      port: 3000
      targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shredis-autoscaler
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shredis-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics: 
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
